### ISSUE TITLE
Dropbox ignores autostart option in Ubuntu 18.04

### ISSUE THREAD

**Issue by Andrade** [dropbox/nautilus-dropbox#47] opened 2018-05-29 15:36 UTC
I don't want Dropbox to start automatically during boot.

* I installed nautilus-dropbox in a fresh version of Ubuntu 18.04
    * Minimal install of the OS, and
    * Installed the daemon from official Ubuntu repositories.
* The app does not respect the *Start Dropbox on system startup* option.
* I've noticed the dropbox file in `~/.config/autostart` is always created¹ whenever the Dropbox app is started (from GUI or CLI).

¹ What this means is that I can manually delete the file or issue `$ dropbox autostart n` after starting the app, and on next restart of the app the file reappears.

---

My current workaround is to issue `$ dropbox autostart n` after starting dropbox since I rarely use dropbox on that machine.

**Comment by nipunn1313** [comment] 2018-05-29 18:02
Hi - thanks for the report!
The current intended behavior is for you to issue `dropbox autostart n` and to have that persist across restarts.

Can you report on what happens with the following steps
1) Start the Dropbox CLI on linux
2) Issue `dropbox autostart n`
3) Reboot your machine  [ Dropbox should not autostart ]
4) Reboot your machine again [ Dropbox should continue to not autostart ]

Can you elaborate (potentially providing screenshots) of the issue you're seeing?

**Comment by Andrade** [comment] 2018-05-30 10:40
I'm currently not near the machine with Ubuntu 18.04, but the behavior you describe is correct. The `dropbox autostart` command works fine as far as I can tell.

The problem happens if I then (after issuing the command) start Dropbox (via CLI or GUI). This creates a file at `~/.config/autostart/dropbox.desktop` that makes Dropbox autostart during reboot.

There is an option in the GUI that is supposed to disable autostart, and mine is indeed disabled (the box is not checked), but that checkbox appears to do nothing.

---

Continuing the steps you provided:

5. Start Dropbox on linux
6. Quit Dropbox
7. Reboot machine [ Dropbox autostarts, but shouldn't ]

**Comment by nipunn1313** [comment] 2018-06-03 03:50
Ah I see.

For context, the nautilus-dropbox CLI typically operates by communicating with the Dropbox app over a socket.

Running `dropbox autostart n` here on the CLI (https://github.com/dropbox/nautilus-dropbox/blob/a9df18bf3bc56254f1374107d6538fb74151dfe6/dropbox.in#L1425) will change the autostart value directly without talking to the Dropbox App.

However, the Dropbox application also internally manages the autostart state separately. It sounds like there are two bugs suggested here by the evidence.

1) The CLI and the Dropbox Application manage autostart independently
2) The Dropbox application's internal autostart management (via GUI)

1 - solution is likely to have the CLI communicate over the socket to the Dropbox Application
2 - we'll have to look into it to investigate what's going on. It would be really helpful if you could provide us the email associated with your account so we could look at logs, just to make sure we're reproing the same thing. (you can email me directly nipunn@dropbox.com or post it here).

**Comment by Andrade** [comment] 2018-06-05 23:54
I don't feel comfortable providing my Dropbox email address.

In any case, I don't see how Dropbox would have access to the local settings I change on the app (e.g. start on boot, limit download/upload rates, etc) unless the Dropbox app is sending these details back to HQ.

**Comment by nipunn1313** [comment] 2018-06-06 07:30
Dropbox uploads logfiles of operations to Dropbox servers to help debug issues like this (like you inferred). Access to logs is limited within the company to those who require it for debugging.

It is understandable not wanting to share your information. In that case, we can try to reproduce using the steps you described.

Thanks for the report

**Comment by Andrade** [comment] 2018-06-06 09:20
Ah, I see. Thank you for the explanation.

**Comment by samertm** [comment] 2018-06-06 21:01
Hey!

I was able to reproduce the issue, and we have a fix for it internally. If you want to get the fix early, keep an eye on the [Dropbox forums](https://www.dropboxforum.com/t5/Beta-testers/ct-p/101003000) for the v53 beta build, which should go out about two weeks from now. (To install from the forums, untar the tarball into your home directory. It'll unpack the `.dropbox-dist` folder there.)

If you don't want to mess with that, v53 should be released as the stable version about 5 weeks from now. At that point, your Dropbox client should auto update to that version.

**Comment by samertm** [comment] 2018-07-25 00:52
v53 is out, please re-open if this is still an issue.

**Closed by samertm** 2018-07-25 00:52 UTC
